---
- name: Deploy .NET Application to IIS
  hosts: windows
  tasks:
    - name: Install IIS and .NET Hosting Bundle
      win_chocolatey:
        name: dotnet-hosting-6.0
        state: present
        source: https://chocolatey.org/api/v2/

    - name: Ensure IIS is running
      win_service:
        name: W3SVC
        state: started

    - name: Copy application files
      win_copy:
        src: ./weather-app
        dest: C:\inetpub\wwwroot\weather-app

    - name: Build application
      win_shell: |
        cd C:\inetpub\wwwroot\weather-app
        dotnet build -c Release

    - name: Create IIS Site for Weather App
      win_iis_website:
        name: WeatherForecast
        state: started
        physical_path: C:\inetpub\wwwroot\weather-app
        port: 80
        ip: "*"

    - name: Restart IIS
      win_shell: iisreset

- name: Configure Nginx on Linux
  hosts: linux
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy proxy configuration
      copy:
        src: files/proxy.conf
        dest: /etc/nginx/sites-available/proxy.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable proxy configuration
      file:
        src: /etc/nginx/sites-available/proxy.conf
        dest: /etc/nginx/sites-enabled/proxy.conf
        state: link

    - name: Remove default configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      changed_when: false

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
